[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
runner = 'riscv64-unknown-elf-gdb -x ./openocd-semihosting.gdb'
# not available
# runner = "probe-rs run --chip HPM6750 --protocol jtag --chip-description-path ../../HPMicro.yaml"

rustflags = [
    # +zba,+zbb,+zbc,+zbs are not available on hpm67
    "-C",
    "target-feature=+d,+zfh",
    # Linker scripts:
    "-C",
    "link-arg=-Tmemory-ram.x",
    "-C",
    "link-arg=-Tdevice.x",
    "-C",
    "link-arg=-Thpm-link.x",
    "-C",
    "link-arg=-nmagic",
]

[unstable]
build-std = ["core"]

